name: Diamond Storage Check

on:
  pull_request:

jobs:
  check-diamond-storage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-87bc53fc6c874bd4c92d97ed180b949e3a36d78c

      - name: Yarn Install
        run: yarn install --mode=skip-build && yarn allow-scripts

      - name: Setup Forge
        run: yarn workspace @ubiquity/contracts forge:install

      - name: Run Diamond Storage Check
        run: |
          cd ./utils
          yes | npx tsx ./diamond-storage.ts
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
