name: Diamond Storage Check

on:
  push:

jobs:
  check-diamond-storage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-87bc53fc6c874bd4c92d97ed180b949e3a36d78c

      - name: Yarn Install
        run: yarn install --mode=skip-build && yarn allow-scripts

      - name: Setup Forge
        run: yarn workspace @ubiquity/contracts forge:install

      - name: "Download Artifact"
        uses: actions/github-script@v6.3.3
        with:
          script: |
            const fs = require("fs");
            const download_artifact = require('${{ github.workspace }}/utils/download_artifact.js');
            const workflow_run_id = '${{ github.event.workflow_run.id }}';
            const workspace = '${{ github.workspace }}';
            download_artifact({github, context, fs, workflow_run_id, workspace})

      - name: Extract Artifact
        run: unzip pr.zip && unzip pull-request.zip && ls

      - name: Run Diamond Storage Check
        run: |
          yarn build:all
          forge inspect Diamond storage
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr/
