name: Check storage layout

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_storage_layout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

#      - name: Move to contracts
#        run: |
#          ls
#          cd packages/contracts
#          echo "After"
#          ls

      - name: Check storage layout
        uses: Rubilmax/foundry-storage-check@v3.6
        with:
          contract: packages/contracts/src/dollar/facets/ChefFacet.sol:ChefFacet